CREATE DATABASE DB_PROYECTO;

USE DB_PROYECTO;

CREATE TABLE AREA(
		ID_AREA INT NOT NULL AUTO_INCREMENT,
        NOMBRE_AREA VARCHAR(50) NOT NULL,
        TELEFONO_AREA INT NOT NULL,
        estatus INT NOT NULL,
        PRIMARY KEY(ID_AREA)
);

CREATE TABLE CARGO(
		ID_CARGO INT NOT NULL,
        NOMBRE_CARGO VARCHAR(50) NOT NULL,
        estatus INT NOT NULL,
        PRIMARY KEY(ID_CARGO)
);

CREATE TABLE TIPO_USUARIO(
        ID_TIPO_USUARIO INT NOT NULL,
        TIPO_USUARIO VARCHAR(50) NOT NULL,
        estatus INT NOT NULL,
        PRIMARY KEY(ID_TIPO_USUARIO)       
);

CREATE TABLE USUARIO(
		ID_USUARIO INT NOT NULL AUTO_INCREMENT,
        USERNAME VARCHAR(50) NOT NULL,
        PASSWORD VARCHAR(75) NOT NULL,
        ID_TIPO_USUARIO INT NOT NULL,
        estatus INT NOT NULL,
        PRIMARY KEY(ID_USUARIO),
        CONSTRAINT FK_TIPO_USUARIO_USUARIO FOREIGN KEY (ID_TIPO_USUARIO)
		REFERENCES TIPO_USUARIO(ID_TIPO_USUARIO)
);

CREATE TABLE EMPLEADO(
		ID_EMPLEADO INT NOT NULL AUTO_INCREMENT,
        NOMBRE_EMPLEADO VARCHAR(50) NOT NULL,
        APELLIDO_EMPLEADO VARCHAR(50) NOT NULL,
        GENERO_EMPLEADO VARCHAR(10) NOT NULL,
        DIRECCION_EMPLEADO VARCHAR(75) NOT NULL,
        FECHA_NAC_EMP DATE NOT NULL,
        EMAIL_EMPLEADO VARCHAR(50) NOT NULL,
        TELEFONO_EMPLEADO INT NOT NULL,
        ID_AREA INT NOT NULL,
        ID_CARGO INT NOT NULL,
        ID_USUARIO INT NOT NULL,
        estatus INT NOT NULL,
        PRIMARY KEY(ID_EMPLEADO),
		CONSTRAINT FK_AREA_EMPLEADO FOREIGN KEY (ID_AREA)
		REFERENCES AREA(ID_AREA),
        CONSTRAINT FK_CARGO_EMPLEADO FOREIGN KEY (ID_CARGO)
		REFERENCES CARGO(ID_CARGO),
        CONSTRAINT FK_USUARIO_EMPLEADO FOREIGN KEY (ID_USUARIO)
		REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE ESTADO(
		ID_ESTADO INT NOT NULL,
        NOMBRE_ESTADO VARCHAR(50) NOT NULL,
        estatus INT NOT NULL,
        PRIMARY KEY(ID_ESTADO)
);

CREATE TABLE TAREA(
        ID_TAREA INT NOT NULL AUTO_INCREMENT,
        NOMBRE_TAREA VARCHAR(50) NOT NULL,
        DESCRIPCION VARCHAR(100) NOT NULL,
        ID_EMPLEADO INT NOT NULL,
        ID_ESTADO INT NOT NULL,
        ID_ASSIGN_BY INT NOT NULL,
        estatus INT NOT NULL,
        PRIMARY KEY(ID_TAREA),
        CONSTRAINT FK_EMPLEADO_TAREA FOREIGN KEY (ID_EMPLEADO)
		REFERENCES EMPLEADO(ID_EMPLEADO),
        CONSTRAINT FK_ESTADO_TAREA FOREIGN KEY (ID_ESTADO)
		REFERENCES ESTADO(ID_ESTADO),
        CONSTRAINT FK_ASIGNACION_TAREA FOREIGN KEY (ID_ASSIGN_BY)
		REFERENCES EMPLEADO(ID_EMPLEADO)
);

CREATE TABLE HISTORIAL(
        ID_TAREA INT NOT NULL,
        FECHA_MODIFICACION DATE NOT NULL,
        ID_ANT_ESTADO INT NOT NULL,
        ID_NUV_ESTADO INT NOT NULL,
        estatus INT NOT NULL,
        PRIMARY KEY(ID_HISTORIAL),       
		CONSTRAINT FK_TAREA_HISTORIAL FOREIGN KEY (ID_TAREA)
		REFERENCES TAREA(ID_TAREA),
        CONSTRAINT FK_ANT_ESTADO_HISTORIAL FOREIGN KEY (ID_ANT_ESTADO)
		REFERENCES ESTADO(ID_ESTADO),
        CONSTRAINT FK_NUV_ESTADO_HISTORIAL FOREIGN KEY (ID_NUV_ESTADO)
		REFERENCES ESTADO(ID_ESTADO)
);

CREATE VIEW vEMPLEADO_SELECT AS 
SELECT e.ID_EMPLEADO, e.NOMBRE_EMPLEADO, e.APELLIDO_EMPLEADO, e.GENERO_EMPLEADO, e.DIRECCION_EMPLEADO, e.FECHA_NAC_EMP, e.EMAIL_EMPLEADO, e.TELEFONO_EMPLEADO, a.NOMBRE_AREA AS AREA, c.NOMBRE_CARGO AS CARGO, u.USERNAME AS USUARIO 
FROM EMPLEADO e 
INNER JOIN AREA a ON a.ID_AREA = e.ID_AREA
INNER JOIN CARGO c ON c.ID_CARGO = e.ID_CARGO
INNER JOIN USUARIO u ON u.ID_USUARIO = e.ID_USUARIO
WHERE e.estatus = 1;
